# Set theme
remote_theme: daviddarnes/alembic@main

# File excludes
exclude:
- README.md
- Gemfile
- Gemfile.lock

# Set plugins
plugins:
- jekyll-sitemap
- jekyll-mentions
- jekyll-paginate
- jekyll-seo-tag
- jekyll-redirect-from
- jekyll-feed
- jekyll-commonmark
- jekyll-include-cache
- jemoji
- jekyll-remote-theme

# Site settings
url: 'https://mydomain.com'
title: 'GenAI For Good'
description: 'UCSD Data Science Capstone 2025'
permalink: pretty
logo: "/assets/images/logo3.png"

# Pagination
paginate: 5
paginate_path: examples/page:num

# Header nav
navigation_header:
- title: Home
  url: /
- title: About
  url: /about/
- title: Examples
  url: /examples/

# Footer nav
navigation_footer:
- title: Back to top
  url: "#top"

# Collections
collections:
  posts:
    title: Example Outputs From Our Project
    output: true
    description: "Through testing, we have generated a number of outputs that we believe are valuable for showcasing the capabilities of our model. Here are some examples that best demonstrate the details between different prompting settings."
    feature_text: |
      # Examples
    feature_image: "https://picsum.photos/2560/600?image=866"

# Collection settings
defaults:
  -
    scope:
      path: ""
      type: "posts"
    values:
      layout: post # Set the default layout for posts
  -
    scope:
      path: ""
      type: "pages"
    values:
      layout: page # Set the default layout for pages
